name: Mongo Github actions
run-name: IP Checker
on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: IP Verifying
        uses: actions/checkout@v2
      - name: Check IP address for system
        run: curl https://api.ipify.org